name: ADMINTOOLS #Im retarded
version: '${project.version}'
main: com.plugin.fulladmintools.AdminToolsPlugin
api-version: '1.19'
author: 7FULL
description: Admin Tools
commands:
  admin:
    description: Opens up the admin menu
    usage: /<command>
    aliases:
      - admintools
      - atools
  banList:
    description: Opens up the ban list (When do it from the console it will be sent to the console)
    usage: /<command>
    aliases:
      - banl
  unBan:
    description: Unban a player
    usage: /<command> <player>
    aliases:
      - uban
  ban:
    description: Ban a player
    usage: /<command> <player> <reason> [time]
  banIp:
    description: Ban a player ip
    usage: /<command> <ip>
  unBanIp:
    description: Unban a player ip
    usage: /<command> <ip>
  banMenu:
    description: Opens up the ban menu
    usage: /<command>
    aliases:
      - banm
  unBanMenu:
    description: Opens up the unban menu
    usage: /<command>
    aliases:
      - unbanm
  freeze:
    description: Freeze a player
    usage: /<command> <player>
  unFreeze:
    description: Unfreeze a player
    usage: /<command> <player>
  freezeMenu:
    description: Opens up the freeze menu
    usage: /<command>
    aliases:
      - freezem
  unFreezeMenu:
        description: Opens up the unfreeze menu
        usage: /<command>
        aliases:
            - unfreezem
  kick:
    description: Kick a player
    usage: /<command> <player> <reason>
  kickMenu:
    description: Opens up the kick menu
    usage: /<command>
    aliases:
      - kickm
